config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sessions/new'
  resources :books, only: %i[create new index]
  resources :members, only: %i[create new index]
  resources :book_rentals, only: %i[create new index]
  resources :returns, only: %i[create new]
  resources :member_book_rentals, only: %i[index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'books#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/controllers/returns_controller.rb
class ReturnsController < ApplicationController
  before_action :authorize_book_rental
  before_action :get_book_rental, only: [:new]

  def new
    @book_rental = BookRental.new
  end

  def create
    @book_rentals = BookRental.current.where(member_id: return_params[:member_id], id: return_params[:book_rental_ids])
    if @book_rentals.count.zero?
      flash[:form_error] = I18n.t('book_rentals_not_found_for_given_member')
    else
      @book_rentals.update(returned_on: return_params[:returned_on])
      flash[:snack_success] = I18n.t('successfully_returned_books_for_member', member_id: return_params[:member_id])
    end

    redirect_to new_return_path
  end

  def return_params
    params
      .require(:return)
      .permit(:member_id, :returned_on, book_rental_ids: [])
  end

  private

  def authorize_book_rental
    authorize BookRental
  end

  def get_book_rental
    @book_rental = BookRental.find_by(id: params[:book_rental_id]) || BookRental.new
  end
end

app/helpers/returns_helper.rb
module ReturnsHelper
end

app/views/returns/new.html.erb
<div class="flex justify-center">
  <div class="w-2/3 flex justify-center"
       data-controller="returns-form"
       data-returns-form-url-value="<%= member_book_rentals_path %>"
       data-returns-form-initial-member-id-value="<%= params.dig(:member_id) %>"
  >
    <%= form_with(url: returns_path, scope: :return, local: true, class: "flex flex-col w-full bg-white shadow-md border rounded-md p-12") do |f| %>
      <p class="text-4xl font-black mb-4"><%= t('return') %></p>
      <%= render 'shared/form_error_messages' %>
      <div class="flex flex-col mb-6">
        <%= f.label :member_id, t('member'), class: "block mb-2 font-medium required-field-label" %>
        <%= f.select :member_id, {}, {}, {
          placeholder: t('search_member_by_name_id_or_personal_number'),
          required: true,
          class: "shadow border px-4 py-2 w-full rounded",
          data: {
            controller: 'searchable-member-select',
            searchable_member_select_url_value: members_path,
            searchable_member_select_initial_item_value: params.dig(:member_id),
            action: "returns-form#handleMemberIdChange"
          }
        } %>
      </div>
      <div class="flex flex-col mb-6">
        <%= f.label :returned_on, t('returned_on'), class: "block mb-2 font-medium required-field-label" %>
        <%= f.date_field :returned_on, {
          value: Date.today,
          max: Date.today,
          required: true,
          class: "shadow border px-4 py-2 w-full rounded",
          data: { action: "returns-form#handleReturningDateChange" }
        }
        %>
      </div>
      <div class="mb-6">
        <label for="books-list-container" class="block mb-2 font-medium required-field-label"><%= t('books') %></label>
        <div
          id="books-list-container"
          class="flex align-items-stretch min-h-24 w-full rounded-md border shadow-md"
          data-returns-form-target="booksList"
        >
        </div>
      </div>
      <div class="flex flex-col mb-6">
        <%= label_tag :total_fine, t('total_fine'), class: "block mb-2 font-medium" %>
        <div id="total_fine" class="text-3xl font-bold">&#8377; <span data-returns-form-target="totalFine">0</span>
        </div>
      </div>
      <%= f.submit t('return_verb'), class: "btn-primary" %>
    <% end %>
  </div>
</div>