config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'sessions/new'
  resources :books, only: %i[create new index]
  resources :members, only: %i[create new index]
  resources :book_rentals, only: %i[create new index]
  resources :returns, only: %i[create new]
  resources :member_book_rentals, only: %i[index]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'books#index'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
end

app/models/book_rental.rb
class BookRental < ApplicationRecord
  # Model Column Definition
  # t.bigint "book_id", null: false
  # t.bigint "member_id", null: false
  # t.date "issued_on", default: -> { "CURRENT_TIMESTAMP" }
  # t.date "returned_on"
  # t.datetime "created_at", precision: 6, null: false
  # t.datetime "updated_at", precision: 6, null: false
  # t.index ["book_id"], name: "index_book_rentals_on_book_id"
  # t.index ["member_id"], name: "index_book_rentals_on_member_id"

  include Filterable

  include PgSearch::Model

  DUE_BY_DAYS = 15
  FINE_PER_DAY = 1

  MAX_RENTALS = 10
  belongs_to :book
  belongs_to :member

  validate :book_is_available, :member_has_only_max_rentals, on: :create

  scope :current, -> { where(returned_on: nil) }

  pg_search_scope :search_by_name,
                  associated_against: {
                    book: :name,
                    member: :name
                  },
                  using: {
                    tsearch: { prefix: true }
                  }

  def self.search(query, max_results=nil)
    if /^\d+$/.match(query.to_s)
      search_by_id(query).limit(max_results)
    elsif query.present?
      search_by_name(query).limit(max_results)
    else
      all.limit(max_results)
    end
  end

  def self.search_by_id(search_id)
    where(book_id: search_id).or(where(member_id: search_id))
  end

  def self.filter_by_show_all(show_all)
    case show_all
    when 'true', true
      all
    else
      current
    end
  end

  def borrower_name_id
    "#{member.name} ##{member.id}"
  end

  def borrowed_book
    "#{book.name} ##{book.id}"
  end

  def returned?
    !returned_on.nil?
  end

  def due_by
    (issued_on || 1.day.ago) + DUE_BY_DAYS.days
  end

  def fine(returned_on = Date.today)
    if returned? || due_by >= returned_on
      0
    else
      ((returned_on - due_by) * FINE_PER_DAY).to_f
    end
  end

  private

  def book_is_available
    errors.add(:base, I18n.t('book_not_available')) unless book.available?
  end

  def member_has_only_max_rentals
    errors.add(:member, I18n.t('member_borrowed_max_books')) if member.book_rentals.current.count >= MAX_RENTALS
  end
end

app/controllers/book_rentals_controller.rb
class BookRentalsController < ApplicationController
  def index
    authorize BookRental
    @pagy, @book_rentals = pagy(BookRental
                                  .includes(:book, :member)
                                  .filter_by_show_all(book_rental_filter_params[:show_all])
                                  .search(book_rental_filter_params[:search])
                                  .order(issued_on: :desc))
  end

  def new
    authorize BookRental
    @book_rental = BookRental.new
  end

  def create
    authorize BookRental
    @book_rental = BookRental.create(book_rental_params)
    if @book_rental.valid?
      flash[:snack_success] = I18n.t('successfully_created_rental_due_by', due_by: @book_rental.due_by)
      redirect_to book_rentals_path
    else
      flash.now[:form_errors] = @book_rental.errors.full_messages
      render 'new'
    end
  end

  private

  def book_rental_params
    params
      .require(:book_rental)
      .transform_values { |x| x.strip.gsub(/\s+/, ' ') if x.respond_to?('strip') }
      .reject { |_k, v| v.blank? }
      .permit(:book_id, :member_id, :issued_on)
  end

  def book_rental_filter_params
    params
      .transform_values { |x| x.strip.gsub(/\s+/, ' ') if x.respond_to?('strip') }
      .permit(:search, :show_all)
  end
end

app/helpers/book_rentals_helper.rb
module BookRentalsHelper
end

app/views/book_rentals/index.html.erb
<div class="flex justify-between mb-2">
  <div class="text-5xl font-black mb-4"><%= t('book_rentals') %></div>
  <div>
    <button class="rounded-md py-2 px-4 text-lg text-gray-500 border border-gray-400 font-semibold">
      <%= link_to "+ #{t('new_rental')}", new_book_rental_path %>
    </button>
  </div>
</div>

<div class="my-4">
  <%= form_with url: book_rentals_path, method: :get, data: { controller: 'search-form', search_form_target: 'form' } do |f| %>
    <div class="flex flex-row gap-2">
      <%= f.search_field :search, {
        placeholder: t('search_by_book_or_member_name'),
        value: params.dig(:search),
        class: "shadow border px-4 py-2 w-full rounded",
        data: { search_form_target: 'text' }
      } %>
      <%= f.submit t('search'), class: "btn-primary" %>
      <%= button_tag t('reset'), type: :reset, data: { action: 'search-form#reset' }, class: "btn-secondary" %>
    </div>
    <div class="p-3">
      <%= f.check_box :show_all, {
        class: 'mr-1',
        include_hidden: false,
        checked: params.dig(:show_all) == 'true',
        onchange: ("this.form.submit()")
      }, 'true', 'false' %>
      <%= f.label :show_all, t('show_all'), class: 'text-gray-700' %>
    </div>
  <% end %>
</div>

<div class="overflow-x-auto">
  <table class="index-table">
    <thead>
      <tr>
        <th><%= t('activerecord.attributes.book_rental.id') %></th>
        <th><%= t('activerecord.models.book') %></th>
        <th><%= t('activerecord.models.member') %></th>
        <th><%= t('activerecord.attributes.member.phone') %></th>
        <th><%= t('activerecord.attributes.book_rental.issued_on') %></th>
        <th><%= t('activerecord.attributes.book_rental.due_by') %></th>
        <th><%= t('activerecord.attributes.book_rental.returned_on') %></th>
      </tr>
    </thead>
    <tbody>
    <% @book_rentals.each do |book_rental| %>
      <tr>
        <td><%= book_rental.id %></td>
        <td><%= book_rental.borrowed_book %></td>
        <td><%= book_rental.borrower_name_id %></td>
        <td><%= book_rental.borrower_phone %></td>
        <td><%= book_rental.issued_on&.to_formatted_s(:long) %></td>
        <td><%= book_rental.due_by&.to_formatted_s(:long) %></td>
        <td>
          <% if book_rental.returned? %>
            <%= book_rental.returned_on&.to_formatted_s(:long) %>
          <% else %>
            <%= link_to(t('return_verb'), new_return_path(member_id: book_rental.member.id), class: 'link-primary') %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>
<%= render partial: 'shared/pagination_bar', locals: { pagy: @pagy } %>

app/views/book_rentals/new.html.erb
<div class="flex justify-center">
  <div class="w-2/3 flex justify-center">
    <%= form_with(model: @book_rental, local: true, class: "flex flex-col w-full bg-white shadow-md border rounded-md p-12") do |f| %>
      <p class="text-4xl font-black mb-4"><%= t('create_book_rental') %></p>
      <%= render 'shared/form_error_messages' %>
      <div class="flex flex-col mb-6">
        <%= f.label :book_id, t('book_label'), class: "block mb-2 font-medium required-field-label" %>
        <%= f.select :book_id, {}, {}, {
          placeholder: t('search_book_by_id_name_or_author_name'),
          required: true,
          class: "shadow border px-4 py-2 w-full rounded",
          data: {
            controller: 'searchable-book-select',
            searchable_book_select_url_value: books_path,
            searchable_book_select_filter_params_value: { availability: true }
          }
        } %>
      </div>
      <div class="flex flex-col mb-6">
        <%= f.label :member_id, t('member_label'), class: "block mb-2 font-medium required-field-label" %>
        <%= f.select :member_id, {}, {}, {
          placeholder: t('search_member_by_name_id_or_personal_number'),
          required: true,
          class: "shadow border px-4 py-2 w-full rounded",
          data: {
            controller: 'searchable-member-select',
            searchable_member_select_url_value: members_path,
            searchable_member_select_filter_params_value: { can_rent: true },
            searchable_member_select_initial_item_value: { book_id: params.dig(:member_id) }
          }
        } %>
      </div>
      <div class="flex flex-col mb-6">
        <%= f.label :issued_on, t('issued_on_label'), class: "block mb-2 font-medium" %>
        <%= f.date_field :issued_on, value: Date.today, class: "shadow border px-4 py-2 w-full rounded" %>
      </div>
      <%= f.submit t('create'), class: "btn-primary" %>
    <% end %>
  </div>
</div>